package snoopy.didit.skill

enum class Skill(
    val number: Int,
    val skillName: String,
) {
    ADOBE_CREATIVE_CLOUD(1, "Adobe Creative Cloud (Photoshop, Illustrator, XD)"),
    AIRTABLE(2, "Airtable"),
    AMPLITUDE(3, "Amplitude"),
    APACHE_AIRFLOW(4, "Apache Airflow"),
    APACHE_HADOOP(5, "Apache Hadoop"),
    APACHE_KAFKA(6, "Apache Kafka"),
    APACHE_SPARK(7, "Apache Spark"),
    APACHE_SUPERSET(8, "Apache Superset"),
    APPDYNAMICS(9, "AppDynamics"),
    ASANA(10, "Asana"),
    AWS(11, "AWS (EC2, S3, RDS, Lambda, SageMaker)"),
    AZURE_DEVOPS(12, "Azure DevOps"),
    BACKSTAGE(13, "Backstage"),
    BALSAMIQ(14, "Balsamiq"),
    BITBUCKET(15, "Bitbucket"),
    BITRISE(16, "Bitrise"),
    BROWSERSTACK(17, "BrowserStack"),
    CIRCLECI(18, "CircleCI"),
    CLICKUP(19, "ClickUp"),
    CONFLUENCE(20, "Confluence"),
    CONTENTFUL(21, "Contentful"),
    CYPRESS(22, "Cypress"),
    DATA_STUDIO(23, "Data Studio"),
    DATADOG(24, "DataDog"),
    DBT(25, "dbt (Data Build Tool)"),
    DOCKER(26, "Docker"),
    DROPBOX(27, "Dropbox"),
    ELASTICSEARCH(28, "ElasticSearch"),
    EMACS(29, "Emacs"),
    EXPO(30, "Expo"),
    EXPRESS_JS(31, "Express.js"),
    FIGMA(32, "Figma"),
    FIREBASE(33, "Firebase"),
    FLATICON(34, "Flaticon"),
    FLUTTER(35, "Flutter"),
    FRAMER(36, "Framer"),
    FRESHDESK(37, "Freshdesk"),
    FRESHSERVICE(38, "Freshservice"),
    GIT(39, "Git"),
    GITHUB(40, "GitHub"),
    GITLAB(41, "GitLab"),
    GOOGLE_ANALYTICS(42, "Google Analytics"),
    GOOGLE_CLOUD_PLATFORM(43, "Google Cloud Platform (GCP)"),
    GRAFANA(44, "Grafana"),
    GRAYLOG(45, "Graylog"),
    HEAP(46, "Heap"),
    HOOTSUITE(47, "Hootsuite"),
    HUBSPOT(48, "HubSpot"),
    HIBERNATE(49, "Hibernate"),
    HOTJAR(50, "Hotjar"),
    INVISION(51, "InVision"),
    INTELLIJ_IDEA(52, "IntelliJ IDEA"),
    INTERCOM(53, "Intercom"),
    IONIC(54, "Ionic"),
    JIRA(55, "JIRA"),
    JIRA_SERVICE_DESK(56, "JIRA Service Desk"),
    JUPYTER_NOTEBOOK(57, "Jupyter Notebook"),
    JENKINS(58, "Jenkins"),
    KUBERNETES(59, "Kubernetes"),
    KAFKA(60, "Kafka"),
    KEYCLOAK(61, "Keycloak"),
    KUBEFLOW(62, "Kubeflow"),
    LOOKER(63, "Looker"),
    LOGGLY(64, "Loggly"),
    LOGSTASH(65, "Logstash"),
    MARKETO(66, "Marketo"),
    MATOMO(67, "Matomo"),
    METABASE(68, "Metabase"),
    MICROSOFT_AZURE(69, "Microsoft Azure"),
    MICROSOFT_OFFICE_365(70, "Microsoft Office 365"),
    MICROSOFT_POWER_AUTOMATE(71, "Microsoft Power Automate"),
    MICROSOFT_POWER_APPS(72, "Microsoft Power Apps"),
    MICROSOFT_TEAMS(73, "Microsoft Teams"),
    MIRI_CANVAS(74, "Miri Canvas"),
    MIXPANEL(75, "Mixpanel"),
    MIRO(76, "Miro"),
    MONGODB(77, "MongoDB"),
    MULESOFT(78, "Mulesoft"),
    NAGIOS(79, "Nagios"),
    NETLIFY(80, "Netlify"),
    NOTION(81, "Notion"),
    NGINX(82, "Nginx"),
    NEW_RELIC(83, "New Relic"),
    OPENAPI(84, "OpenAPI"),
    OPTIMIZELY(85, "Optimizely"),
    ORACLE_DB(86, "Oracle DB"),
    OVERLEAF(87, "Overleaf"),
    PAGERDUTY(88, "PagerDuty"),
    PENDO(89, "Pendo"),
    POWER_BI(90, "Power BI"),
    POSTGRESQL(91, "PostgreSQL"),
    PYCHARM(92, "PyCharm"),
    POSTMAN(93, "Postman"),
    QLIKVIEW(94, "QlikView"),
    QUIP(95, "Quip"),
    REACT(96, "React"),
    REDIS(97, "Redis"),
    REDUX(98, "Redux"),
    ROLLBAR(99, "Rollbar"),
    SALESFORCE(100, "Salesforce"),
    SEMRUSH(101, "SEMrush"),
    SENDGRID(102, "SendGrid"),
    SKETCH(103, "Sketch"),
    SLACK(104, "Slack"),
    SNOWFLAKE(105, "Snowflake"),
    SPLUNK(106, "Splunk"),
    SPRING_BOOT(107, "Spring Boot"),
    SUMO_LOGIC(108, "Sumo Logic"),
    SNYK(109, "Snyk"),
    SUPERSET(110, "Superset"),
    TABLEAU(111, "Tableau"),
    TRELLO(112, "Trello"),
    TESTRAIL(113, "TestRail"),
    TRAVIS_CI(114, "Travis CI"),
    TYPEFORM(115, "Typeform"),
    UBUNTU(116, "Ubuntu"),
    UNITY(117, "Unity"),
    UNREAL_ENGINE(118, "Unreal Engine"),
    VS_CODE(119, "VS Code"),
    VERCEL(120, "Vercel"),
    VMWARE(121, "VMware"),
    WEBFLOW(122, "Webflow"),
    WEBPACK(123, "Webpack"),
    WORDPRESS(124, "WordPress"),
    WRIKE(125, "Wrike"),
    XAMARIN(126, "Xamarin"),
    XCODE(127, "Xcode"),
    YOAST_SEO(128, "Yoast SEO"),
    ZAPIER(129, "Zapier"),
    ZEPLIN(130, "Zeplin"),
    ZENDESK(131, "Zendesk"),
    ;

    companion object {
        fun toSkill(number: Int): Skill {
            return entries.first { it.number == number }
        }

        fun toInt(skill: Skill): Int {
            return skill.number
        }

        fun getAll() = entries.map { it.number to it.name }
    }
}
