spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


---
spring.config.activate.on-profile: live

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp-user}
    password: ${smtp-pwd}
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
